[changelog]
header = ""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim | replace(from=" feat: ", to=" ") | replace(from=" fix: ", to=" ") | replace(from=" refactor: ", to=" ") | replace(from=" docs: ", to=" ") | replace(from=" perf: ", to=" ") | replace(from=" test: ", to=" ") | replace(from=" chore: ", to=" ") | replace(from=" style: ", to=" ") | replace(from=" ci: ", to=" ") | replace(from=" remove: ", to=" ") | replace(from=" polish: ", to=" ") | replace(from=" assets: ", to=" ") | replace(from=" wip: ", to=" ") }}
{%- endfor %}

{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
filter_commits = true
tag_pattern = "v[0-9]*"
sort_commits = "newest"

commit_parsers = [
  { message = ".*feat", group = "⛰️ Features" },
  { message = ".*fix", group = "🐛 Bug Fixes" },
  { message = ".*refactor", group = "🚜 Refactor" },
  { message = ".*docs", group = "📚 Documentation" },
  { message = ".*perf", group = "⚡ Performance" },
  { message = ".*test", group = "🧪 Testing" },
  { message = ".*(chore|style|ci|remove|polish|assets)", group = "⚙️ Miscellaneous Tasks" },
  { message = ".*", group = "💼 Other" },
]
